import builtins
import sys
from typing import (
    Any,
    Final,
)

from strictyaml.ruamel import scalarstring
from strictyaml.ruamel.comments import (
    CommentedMap,
    CommentedSeq,
)
from strictyaml.scalar import ScalarValidator
from strictyaml.validators import Validator
from strictyaml.yamllocation import YAMLChunk
from typing_extensions import Self

# from _typeshed import _KT, _VT

__all__ = ("YAML",)

# _K = TypeVar("_K")
# _V = TypeVar("_V")

unicode: Final[type[builtins.str]]

if sys.version_info >= (3, 7):
    # On 3.7+, strictyaml sets OrderedDict = dict
    OrderedDict: Final[type[builtins.dict[Any, Any]]]  # [_KT, _VT]
else:
    from collections import OrderedDict as _OrderedDict

    OrderedDict: Final[type[_OrderedDict[Any, Any]]]  # [_KT, _VT]

class YAMLIterator:
    def __init__(self, yaml_object: "YAML") -> None: ...  # noqa: Y020
    def __iter__(self) -> Self: ...
    def next(self) -> "YAML": ...  # noqa: Y020
    def __next__(self) -> "YAML": ...  # noqa: Y020

class YAML:
    _value: CommentedMap | CommentedSeq | scalarstring.ScalarString | Any
    _text: str | None
    _chunk: YAMLChunk
    _validator: Validator | None
    _selected_validator: Validator | None

    def __init__(
        self,
        value: YAMLChunk | Self | Any,
        validator: Validator | None = None,
    ) -> None: ...
    def __int__(self) -> int: ...
    def __unicode__(self) -> str: ...
    def revalidate(self, schema: Validator) -> None: ...
    @property
    def data(self) -> dict[Any, Any] | list[Any] | str | Any: ...
    def as_marked_up(self) -> CommentedSeq | CommentedMap: ...
    @property
    def start_line(self) -> int: ...
    @property
    def end_line(self) -> int: ...
    def lines(self) -> list[str]: ...
    def lines_before(self, how_many: int) -> list[str]: ...
    def lines_after(self, how_many: int) -> list[str]: ...
    def __float__(self) -> float: ...
    def __bool__(self) -> bool: ...
    def _strictindex(self, index: Self | int) -> Any | int: ...
    def __nonzero__(self) -> bool: ...
    def __getitem__(self, index: Self | int) -> Validator: ...
    def __setitem__(self, index: Self | int, value: Validator) -> None: ...
    def __delitem__(self, index: Self | int) -> None: ...
    def __hash__(self) -> int: ...
    def __len__(self) -> int: ...
    def as_yaml(self) -> str: ...
    def items(self) -> list[tuple[type[ScalarValidator], Validator]]: ...
    def keys(self) -> list[type[ScalarValidator]]: ...
    def values(self) -> list[Validator]: ...
    def get(
        self,
        index: Self | int,
        default: Validator | None = None,
    ) -> Validator | None: ...
    def __contains__(
        self,
        item: CommentedSeq | CommentedMap | Validator,
    ) -> bool: ...
    def __iter__(self) -> YAMLIterator: ...
    @property
    def validator(self) -> Validator: ...
    @property
    def text(self) -> str: ...
    def copy(self) -> Self: ...
    def __gt__(self, val: CommentedMap | CommentedSeq | Validator) -> bool: ...
    def __lt__(self, val: CommentedMap | CommentedSeq | Validator) -> bool: ...
    # rtype follows YAML.data
    @property
    def value(
        self,
    ) -> CommentedMap | CommentedSeq | scalarstring.ScalarString | Any: ...
    def is_mapping(self) -> bool: ...
    def is_sequence(self) -> bool: ...
    def is_scalar(self) -> bool: ...
    @property
    def scalar(self) -> Validator: ...
    # don't know the typing of ruamelparsed
    def whole_document(self) -> Any: ...
    def __eq__(self, value: object) -> bool: ...
    def __ne__(self, value: object) -> bool: ...
