import builtins
import decimal
from datetime import datetime
from typing import (
    Any,
    Final,
)

from strictyaml.representation import YAML
from strictyaml.validators import Validator
from strictyaml.yamllocation import YAMLChunk

__all__ = (
    "Bool",
    "CommaSeparated",
    "Datetime",
    "Decimal",
    "Email",
    "EmptyDict",
    "EmptyList",
    "EmptyNone",
    "Enum",
    "Float",
    "HexInt",
    "Int",
    "NullNone",
    "Regex",
    "ScalarValidator",
    "Str",
    "Url",
)

unicode: Final[type[builtins.str]]

class ScalarValidator(Validator):
    @property
    def rule_description(self) -> str: ...
    def __call__(self, chunk: YAMLChunk) -> YAML: ...
    def validate(self, chunk: YAMLChunk) -> Any: ...
    def should_be_string(self, data: Any, message: str) -> None: ...
    def validate_scalar(self, chunk: YAMLChunk) -> Any: ...

class Enum(ScalarValidator):
    _item_validator: ScalarValidator
    _restricted_to: list[Any]

    def __init__(
        self,
        restricted_to: list[Any],
        item_validator: ScalarValidator | None = None,
    ) -> None: ...
    def validate_scalar(self, chunk: YAMLChunk) -> Any: ...
    def to_yaml(self, data: Any) -> YAML: ...

class CommaSeparated(ScalarValidator):
    def __init__(self, item_validator: ScalarValidator) -> None: ...
    def validate_scalar(self, chunk: YAMLChunk) -> list[Any]: ...
    def to_yaml(self, data: str | list[Any]) -> YAML: ...

class Regex(ScalarValidator):
    def __init__(self, regular_expression: str) -> None: ...
    def validate_scalar(self, chunk: YAMLChunk) -> str: ...
    def to_yaml(self, data: str) -> YAML: ...

class Email(Regex):
    def __init__(self) -> None: ...

class Url(ScalarValidator):
    def __is_absolute_url(self, raw: str) -> bool: ...
    def validate_scalar(self, chunk: YAMLChunk) -> str: ...
    def to_yaml(self, data: str) -> YAML: ...

class Str(ScalarValidator):
    def validate_scalar(self, chunk: YAMLChunk) -> str: ...
    def to_yaml(self, data: str) -> YAML: ...

class Int(ScalarValidator):
    def validate_scalar(self, chunk: YAMLChunk) -> int: ...
    def to_yaml(self, data: int | str) -> str: ...

class HexInt(ScalarValidator):
    def validate_scalar(self, chunk: YAMLChunk) -> int: ...
    def to_yaml(self, data: int | str) -> str: ...

class Bool(ScalarValidator):
    def validate_scalar(self, chunk: YAMLChunk) -> bool: ...
    def to_yaml(self, data: str | bool) -> str: ...

class Float(ScalarValidator):
    def validate_scalar(self, chunk: YAMLChunk) -> float: ...
    def to_yaml(self, data: float) -> str: ...

class Decimal(ScalarValidator):
    def validate_scalar(self, chunk: YAMLChunk) -> decimal.Decimal: ...

class Datetime(ScalarValidator):
    def validate_scalar(self, chunk: YAMLChunk) -> datetime: ...
    def to_yaml(self, data: datetime) -> str: ...

class NullNone(ScalarValidator):
    def validate_scalar(self, chunk: YAMLChunk) -> None: ...
    def empty(self, chunk: YAMLChunk) -> None: ...
    def to_yaml(self, data: Any | None) -> str: ...

class EmptyNone(ScalarValidator):
    def validate_scalar(self, chunk: YAMLChunk) -> None: ...
    def empty(self, chunk: YAMLChunk) -> None: ...
    def to_yaml(self, data: Any | None) -> str: ...

class EmptyDict(EmptyNone):
    def empty(self, chunk: YAMLChunk) -> dict[Any, Any]: ...  # type: ignore[override]
    def to_yaml(self, data: Any | None) -> str: ...

class EmptyList(EmptyNone):
    def empty(self, chunk: YAMLChunk) -> list[Any]: ...  # type: ignore[override]
    def to_yaml(self, data: Any | None) -> str: ...
