from typing import Any

from strictyaml.ruamel.comments import (
    CommentedMap,
    CommentedSeq,
)
from strictyaml.yamllocation import YAMLChunk
from typing_extensions import (
    Self,
    TypeAlias,
)

__all__ = ("YAMLPointer",)

SEGMENT: TypeAlias = CommentedMap | CommentedSeq

# _indices Any portion needs a TypeAlias
class YAMLPointer:
    _indices: list[tuple[str, Any]]

    def __init__(self) -> None: ...
    @property
    def last_index(self) -> int: ...
    @property
    def last_val(self) -> YAMLChunk: ...
    @property
    def last_strictkey(self) -> str: ...
    @property
    def last_regularkey(self) -> str: ...
    def val(self, regularkey: str, strictkey: str) -> Self: ...
    def is_val(self) -> bool: ...
    def key(self, regularkey: str, strictkey: str) -> Self: ...
    def is_key(self) -> bool: ...
    def index(self, index: Any) -> Self: ...
    def is_index(self) -> bool: ...
    def textslice(self, start: int, end: int) -> Self: ...
    def is_textslice(self) -> bool: ...
    def parent(self) -> Self: ...
    def make_child_of(self, pointer: Self) -> None: ...
    def _slice_segment(
        self,
        indices: Any,
        segment: SEGMENT,
        include_selected: bool,
    ) -> SEGMENT: ...
    def start_line(self, document: SEGMENT) -> int: ...
    def end_line(self, document: SEGMENT) -> int: ...
    def lines(self, document: SEGMENT) -> list[str]: ...
    def lines_before(self, document: SEGMENT, how_many: int) -> list[str]: ...
    def lines_after(self, document: SEGMENT, how_many: int) -> list[str]: ...
    def _individual_get(
        self,
        segment: SEGMENT,
        index_type: str,
        index: Any,
        strictdoc: bool,
    ) -> SEGMENT: ...
    def get(self, document: SEGMENT, strictdoc: bool = False) -> YAMLChunk: ...
    def set(
        self,
        src_obj: YAMLChunk,
        src_attr: str,
        new_ruamel: YAMLChunk,
        strictdoc: bool = False,
    ) -> None: ...
