import builtins
from typing import (
    Any,
    Final,
)

from strictyaml.representation import YAML
from strictyaml.yamlpointer import YAMLPointer
from typing_extensions import Self

__all__ = ("YAMLChunk",)

unicode: Final[type[builtins.str]]

class YAMLChunk:
    def __init__(
        self,
        ruamelparsed: Any,
        pointer: YAMLPointer | None = None,
        label: str | None = None,
        strictparsed: YAML | None = None,
        key_association: dict[str, str] | None = None,
    ) -> None: ...
    def expecting_but_found(
        self,
        expecting: str,
        found: str | None = None,
    ) -> None: ...
    def while_parsing_found(self, what: str, found: str | None = None) -> None: ...
    def process(self, new_item: Any) -> None: ...
    def is_sequence(self) -> bool: ...
    def is_mapping(self) -> bool: ...
    def is_scalar(self) -> bool: ...
    def found(self) -> str: ...
    def expect_sequence(self, expecting: str = ...) -> list[Self]: ...
    def expect_mapping(self) -> dict[Self, Self]: ...
    def expect_scalar(self, what: str) -> None: ...
    @property
    def label(self) -> str | None: ...
    @property
    def whole_document(self) -> Any: ...
    @property
    def pointer(self) -> YAMLPointer: ...
    def fork(self, strictindex: int, new_value: YAML) -> Self: ...
    def add_key_association(self, unprocessed_key: str, processed_key: str) -> None: ...
    @property
    def key_association(self) -> dict[str, str]: ...
    def make_child_of(self, chunk: Self) -> None: ...
    def _select(self, pointer: YAMLPointer) -> Self: ...
    def index(self, strictindex: int) -> Self: ...
    def ruamelindex(self, strictindex: int) -> int: ...
    def val(self, strictkey: int) -> Self: ...
    def key(self, key: str, strictkey: int | None = None) -> Self: ...
    def textslice(self, start: int, end: int) -> Self: ...
    def start_line(self) -> int: ...
    def end_line(self) -> int: ...
    def lines(self) -> list[str]: ...
    def lines_before(self, how_many: int) -> list[str]: ...
    def lines_after(self, how_many: int) -> list[str]: ...
    @property
    def contents(self) -> Any: ...
    def strictparsed(self) -> Self: ...
