import sys
from collections import OrderedDict
from collections.abc import (
    ItemsView,
    Iterator,
    KeysView,
    Mapping,
    MutableSet,
    Sized,
    ValuesView,
)
from typing import (
    Any,
    ClassVar,
    Final,
)

from strictyaml.ruamel.compat import MutableSliceableSequence
from typing_extensions import Self

__all__ = (
    "CommentedSeq",
    "CommentedKeySeq",
    "CommentedMap",
    "CommentedOrderedMap",
    "CommentedSet",
    "comment_attrib",
    "merge_attrib",
)

comment_attrib: Final[str]
format_attrib: Final[str]
line_col_attrib: Final[str]
merge_attrib: Final[str]
tag_attrib: Final[str]

class ordereddict(OrderedDict):  # type: ignore
    def insert(self, pos: int, key: Any, value: Any) -> None: ...

class Comment:
    __slots__ = (
        "comment",
        "_items",
        "_end",
        "_start",
    )
    attrib: ClassVar[str]

    def __init__(self) -> None: ...
    @property
    def items(self) -> Any: ...
    @property
    def end(self) -> Any: ...
    @end.setter
    def end(self, value: Any) -> None: ...
    @property
    def start(self) -> Any: ...
    @start.setter
    def start(self, value: Any) -> None: ...

def NoComment() -> None: ...

class Format:
    __slots__ = ("_flow_style",)
    attrib: ClassVar[str]

    def __init__(self) -> None: ...
    def set_flow_style(self) -> None: ...
    def set_block_style(self) -> None: ...
    def flow_style(self, default: Any | None = None) -> Any: ...

class LineCol:
    attrib: ClassVar[str]

    def __init__(self) -> None: ...
    def add_kv_line_col(self, key: Any, data: Any) -> None: ...
    def key(self, k: Any) -> Any: ...
    def value(self, k: Any) -> Any: ...
    def _kv(self, k: Any, x0: Any, x1: Any) -> Any: ...
    def item(self, idx: Any) -> Any: ...
    def add_idx_line_col(self, key: Any, data: Any) -> None: ...

class Tag:
    __slots__ = ("value",)
    attrib: ClassVar[str]

    def __init__(self) -> None: ...

class CommentedBase:
    @property
    def ca(self) -> Any: ...
    def yaml_end_comment_extend(
        self,
        comment: Any,
        clear: bool | None = False,
    ) -> None: ...
    def yaml_key_comment_extend(
        self,
        key: Any,
        comment: Any,
        clear: bool | None = False,
    ) -> None: ...
    def yaml_value_comment_extend(
        self,
        key: Any,
        comment: Any,
        clear: bool | None = False,
    ) -> None: ...
    def yaml_set_start_comment(
        self,
        comment: Any,
        indent: Any = 0,
    ) -> None: ...
    def yaml_set_comment_before_after_key(
        self,
        key: Any,
        before: Any | None = None,
        indent: Any | None = 0,
        after: Any | None = None,
        after_indent: Any | None = None,
    ) -> None: ...
    @property
    def fa(self) -> Any: ...
    def yaml_add_eol_comment(
        self,
        comment: Any,
        key: Any | None = ...,
        column: Any | None = None,
    ) -> None: ...
    @property
    def lc(self) -> Any: ...
    def _yaml_set_line_col(self, line: Any, col: Any) -> None: ...
    def _yaml_set_kv_line_col(self, key: Any, data: Any) -> None: ...
    def _yaml_set_idx_line_col(self, key: Any, data: Any) -> None: ...
    @property
    def anchor(self) -> Any: ...
    def yaml_anchor(self) -> Any: ...
    def yaml_set_anchor(
        self,
        value: Any,
        always_dump: bool | None = False,
    ) -> None: ...
    @property
    def tag(self) -> Any: ...
    def yaml_set_tag(self, value: Any) -> None: ...
    def copy_attributes(self, t: Any, memo: Any | None = None) -> None: ...
    def _yaml_add_eol_comment(self, comment: Any, key: Any) -> None: ...
    def _yaml_get_pre_comment(self) -> Any: ...
    def _yaml_get_column(self, key: Any) -> Any: ...

class CommentedSeq(MutableSliceableSequence, list, CommentedBase):  # type: ignore
    __slots__ = (Comment.attrib, "_lst")

    def __init__(self, *args: Any, **kw: Any) -> None: ...
    def __getsingleitem__(self, idx: Any) -> Any: ...
    def __setsingleitem__(self, idx: Any, value: Any) -> None: ...
    def __delsingleitem__(self, idx: Any | None = None) -> None: ...
    def __len__(self) -> int: ...
    def insert(self, idx: Any, val: Any) -> None: ...
    def extend(self, val: Any) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def _yaml_add_comment(self, comment: Any, key: Any | None = ...) -> None: ...
    def _yaml_add_eol_comment(self, comment: Any, key: Any) -> None: ...
    def _yaml_get_columnX(self, key: Any) -> Any: ...
    def _yaml_get_column(self, key: Any) -> Any: ...
    def _yaml_get_pre_comment(self) -> Any: ...
    def __deepcopy__(self, memo: Any) -> Any: ...
    def __add__(self, other: Any) -> Any: ...
    def sort(
        self,
        /,
        *,
        key: Any | None = None,
        reverse: bool | None = False,
    ) -> None: ...

class CommentedKeySeq(tuple, CommentedBase):  # type: ignore
    def _yaml_add_comment(self, comment: Any, key: Any | None = ...) -> None: ...
    def _yaml_add_eol_comment(self, comment: Any, key: Any) -> None: ...
    def _yaml_get_columnX(self, key: Any) -> Any: ...
    def _yaml_get_column(self, key: Any) -> Any: ...
    def _yaml_get_pre_comment(self) -> Any: ...

class CommentedMapView(Sized):
    __slots__ = ("_mapping",)

    def __init__(self, mapping: Any) -> None: ...
    def __len__(self) -> int: ...

class CommentedMapKeysView(CommentedMapView, set):  # type: ignore
    __slots__ = ()

    @classmethod
    def _from_iterable(cls, it: Any) -> Any: ...
    def __contains__(self, key: Any) -> bool: ...
    def __iter__(self) -> Iterator[Any]: ...

class CommentedMapItemsView(CommentedMapView, set):  # type: ignore
    __slots__ = ()

    @classmethod
    def _from_iterable(cls, it: Any) -> Any: ...
    def __contains__(self, item: Any) -> bool: ...
    def __iter__(self) -> Iterator[Any]: ...

class CommentedMapValuesView(CommentedMapView):
    __slots__ = ()

    def __contains__(self, value: Any) -> bool: ...
    def __iter__(self) -> Self: ...

class CommentedMap(ordereddict, CommentedBase):
    __slots__ = (Comment.attrib, "_ok", "_ref")

    def __init__(self, *args: Any, **kw: Any) -> None: ...
    def _yaml_add_comment(
        self,
        comment: Any,
        key: Any | None = ...,
        value: Any | None = ...,
    ) -> None: ...
    def _yaml_add_eol_comment(self, comment: Any, key: Any) -> None: ...
    def _yaml_get_columnX(self, key: Any) -> Any: ...
    def _yaml_get_column(self, key: Any) -> Any: ...
    def _yaml_get_pre_comment(self) -> Any: ...
    def update(self, *vals: Any, **kw: Any) -> None: ...
    def insert(
        self,
        pos: Any,
        key: Any,
        value: Any,
        comment: Any | None = None,
    ) -> None: ...
    def mlget(
        self,
        key: Any,
        default: Any | None = None,
        list_ok: bool | None = False,
    ) -> Any: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def _unmerged_contains(self, key: Any) -> bool | None: ...
    def __contains__(self, key: Any) -> bool: ...
    def get(self, key: Any, default: Any | None = None) -> Any: ...
    def non_merged_items(self) -> Iterator[tuple[Any, Any]]: ...
    def __delitem__(self, key: Any) -> None: ...
    def __iter__(self) -> Iterator[Any]: ...
    def _keys(self) -> Iterator[Any]: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def keys(self) -> KeysView[Any]: ...  # type: ignore[override]
    def values(self) -> ValuesView[Any]: ...  # type: ignore[override]
    def _items(self) -> Any: ...
    def items(self) -> ItemsView[Any, Any]: ...  # type: ignore[override]
    @property
    def merge(self) -> Any: ...
    def copy(self) -> Any: ...
    def add_referent(self, cm: Any) -> None: ...
    def add_yaml_merge(self, value: Any) -> None: ...
    def update_key_value(self, key: Any) -> None: ...
    def __deepcopy__(self, memo: Self) -> Self: ...

@classmethod  # type: ignore
def raise_immutable(cls: Any, *args: Any, **kwargs: Any) -> None: ...

class CommentedKeyMap(CommentedBase, Mapping):  # type: ignore
    __slots__ = (Comment.attrib, "_od")
    def __init__(self, *args: Any, **kw: Any) -> None: ...
    def __getitem__(self, index: Any) -> Any: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __len__(self) -> int: ...
    def __hash__(self) -> int: ...
    @classmethod
    def fromkeys(cls, keys: Any, v: Any | None = None) -> Any: ...
    def _yaml_add_comment(self, comment: Any, key: Any | None = ...) -> None: ...
    def _yaml_add_eol_comment(self, comment: Any, key: Any) -> None: ...
    def _yaml_get_columnX(self, key: Any) -> Any: ...
    def _yaml_get_column(self, key: Any) -> Any: ...
    def _yaml_get_pre_comment(self) -> Any: ...

class CommentedOrderedMap(CommentedMap):
    __slots__ = (Comment.attrib,)

class CommentedSet(MutableSet, CommentedBase):  # type: ignore  # noqa
    __slots__ = (Comment.attrib, "odict")
    def __init__(self, values: Any | None = None) -> None: ...
    def _yaml_add_comment(
        self,
        comment: Any,
        key: Any | None = ...,
        value: Any | None = ...,
    ) -> None: ...
    def _yaml_add_eol_comment(self, comment: Any, key: Any) -> None: ...
    def add(self, value: Any) -> None: ...
    def discard(self, value: Any) -> None: ...
    def __contains__(self, x: Any) -> bool: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __len__(self) -> int: ...

class TaggedScalar(CommentedBase):
    def __init__(
        self,
        value: Any | None = None,
        style: Any | None = None,
        tag: Any | None = None,
    ) -> None: ...

def dump_comments(
    d: Any,
    name: str = "",
    sep: str = ".",
    out: Any = sys.stdout,
) -> None: ...
