from collections.abc import Callable
from typing import (
    Any,
    ClassVar,
    TextIO,
)

from .error import YAMLError
from .util import LazyEval

__all__ = ("ReaderError", "Reader")

class ReaderError(YAMLError):
    def __init__(
        self,
        name: Any,
        position: Any,
        character: Any,
        encoding: Any,
        reason: Any,
    ) -> None: ...

class Reader:
    NON_PRINTABLE: ClassVar[Callable[..., LazyEval]]
    _printable_ascii: ClassVar[str]

    def __init__(self, stream: Any, loader: Any | None = None) -> None: ...
    def reset_reader(self) -> None: ...
    @property
    def stream(self) -> Any: ...
    @stream.setter
    def stream(self, val: Any) -> None: ...
    def peek(self, index: int = 0) -> TextIO: ...
    def prefix(self, length: int = 1) -> Any: ...
    def forward_1_1(self, length: int = 1) -> None: ...
    def forward(self, length: int = 1) -> None: ...
    def get_mark(self) -> Any: ...
    def determine_encoding(self) -> None: ...
    @classmethod
    def _get_non_printable_ascii(cls, data: bytes) -> tuple[int, str] | None: ...
    @classmethod
    def _get_non_printable_regex(cls, data: str) -> tuple[int, str] | None: ...
    @classmethod
    def _get_non_printable(cls, data: bytes | str) -> tuple[int, str] | None: ...
    def check_printable(self, data: Any) -> None: ...
    def update(self, length: int) -> None: ...
    def update_raw(self, size: int | None = None) -> None: ...
